spring:
  profiles: defaultt
  application:
    name: eureka-server-standalone
server:
  port: 8010
eureka:
  instance:
    hostname: eurekahost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: primary
  application:
    name: eureka-server-clustered
server:
  port: 8011
eureka:
  instance:
    hostname: eureka-primary
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: secondary
  application:
    name: eureka-server-clustered
server:
  port: 8012
eureka:
  instance:
    hostname: eureka-secondary
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: tertiary
  application:
    name: eureka-server-clustered
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-tertiary
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/
